# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js Linux Build
on:
  push:
    branches: [ rei-yarn ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: ./scripts/set-dev-version.js
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.77.0
      with:
        ruby-version: 2.7
    - run: ./scripts/bootstrap-env-ubuntu.sh
    - run: yarn run build
    - run: yarn run build-dist
    - run: yarn run build-deb
    - name: Archive develop artifacts
      uses: actions/upload-artifact@v2
      with:
        name: yarn
        path: |
          artifacts/*.deb
          artifacts/*.rpm
